title: Lizz Westman Has A Github Page
author: Lizz Westman
email: github@lizzwestman.com
description: > # this means to ignore newlines until "baseurl:"
  Lizz Westman has a page on github to test out how to use this whole repository and general configuration in its current set up. It also may be used as a place to brag about things she's done too. Unsure!!

# social links
twitter_username: lizzwestman # DO NOT include the @ character, or else the build will fail!
github_username:  lizzwestman # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
